### ISSUE TITLE
TBD: How to use tsmatrixserverlib (Discussion required)

### ISSUE THREAD

**Issue by madguy02** [RocketChat/Rocket.Chat.Federation#24]
Description: How to use tsmatrixserverlib ( a set of rules lib ) for federation. Ideas are welcome
Reference lib : [tsmatrixserverlib](https://github.com/RocketChat/tsmatrixserverlibl)

**Comment by debugdjblade** [comment]
Any development using federation setup with ref lib?

**Comment by sampaiodiego** [comment]
not really.. we have implemented our own federation protocol
