### ISSUE TITLE
Still alive? 

### ISSUE THREAD

**Issue by mbround18** [RocketChat/Rocket.Chat.Federation#3]
Is this project still alive?

**Comment by madguy02** [comment]
yes :D,https://github.com/RocketChat/Rocket.Chat.Federation/blob/tsmatrixlib/tsmatrixserverlib/Readme.md  you are welcome to contribute

**Comment by erlend-sh** [comment]
What's the status of this project now that GSoC has ended?

**Comment by madguy02** [comment]
the project was a part of Rocket.chat summer of code and not exactly under Google(google's summer of code) although the processes were exactly the same.Considering the scope of the project,it is still under development and the low level modules can be seen here : https://github.com/RocketChat/tsmatrixserverlib

**Comment by erlend-sh** [comment]
I see, thanks for the info. I'd love to read a summary post of the last few months of work that's been done in this space. As far as I know RocketChat is the only major team chat app that has committed to Matrix federation. It would help adoption to make this effort more public, and share feedback on any implementation challenges with the Matrix core team,

**Comment by madguy02** [comment]
yes i will definitely do that in upcoming days :)

**Comment by erlend-sh** [comment]
Was anything ever posted? @madguy02 @Sing-Li

**Comment by MikeColes** [comment]
Curious as well. Exploring different chat options. Federation is a preferred ability.

**Comment by madguy02** [comment]
As an update to Rocket.Chat federation, the development on federation is
speeding up at our end and currently focusing on rapid prototyping. We are
yet to finalize on the architecture which will be the best suited one for
Rocket.Chat and hopefully be online within couple of months.

Thanks a lot for holding up with us for a long time.
We are trying very best on our end to launch the first version of
federation ASAP.

**Comment by MikeColes** [comment]
Thanks, @madguy02 . I realize how much work will be going into this (and by that, I'm sure there is so much more that I don't realize)

The effort you and the team put in are appreciated.
